# Generated by Django 3.1.7 on 2021-04-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('cpf', models.TextField(max_length=14)),
                ('born_date', models.DateTimeField()),
                ('rg_pdf', models.FileField(upload_to='documents/')),
                ('cpf_pdf', models.FileField(upload_to='documents/')),
                ('contract_pdf', models.FileField(upload_to='documents/')),
                ('status', models.TextField()),
                ('cancel_reason', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lectureticket',
            },
        ),
    ]
