# Generated by Django 3.1.7 on 2021-04-09 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LectureTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=40)),
                ('cpf', models.TextField(max_length=11)),
                ('born_date', models.DateTimeField()),
                ('rg_pdf_path', models.TextField()),
                ('cpf_pdf_path', models.TextField()),
                ('contract_pdf_path', models.TextField()),
                ('status', models.TextField()),
                ('cancel_reason', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lectureticket',
            },
        ),
    ]
