# Generated by Django 3.1.7 on 2021-04-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_lectureticket_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectureticket',
            name='contract_pdf_path',
        ),
        migrations.RemoveField(
            model_name='lectureticket',
            name='cpf_pdf_path',
        ),
        migrations.RemoveField(
            model_name='lectureticket',
            name='rg_pdf_path',
        ),
        migrations.AddField(
            model_name='lectureticket',
            name='contract_pdf',
            field=models.FileField(default='default', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureticket',
            name='cpf_pdf',
            field=models.FileField(default='default', upload_to='documents/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lectureticket',
            name='rg_pdf',
            field=models.FileField(default='default', upload_to='documents/'),
            preserve_default=False,
        ),
    ]
